### ISSUE TITLE
unfair when use exquisite test_transform 

### ISSUE THREAD

**Issue by zaiquanyang** [zhiweichen0012/LCTR#1]

**Comment by zhiweichen0012** [comment]
First of all, thank you for your attention to this work, the question is explained as follows.

**Comment by zhiweichen0012** [comment]
Thank you for your attention to our work, the issue is explained as follows.

(1)  The test_transform is a common test_transform for WSOL.
(2) We re-implement the baseline and outperform it, which proves the effectiveness of our approach.
(3) More importantly, we did not use the ten crop augmentations in the testing phase as other WSOL methods, and we believe that LCTR will get higher performance after using this augmentation.

Therefore, it is fair to use the test_transform.

**Comment by zaiquanyang** [comment]
非常感谢您的及时热心回复，认可您的说法，最近我在复现一些相关的工作，如果您方便的话，可以加微信向您请教吗


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "zhiweichen0012/LCTR"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年5月14日(星期六) 晚上10:58
***@***.***&gt;;
抄送:&nbsp;"11111603班 ***@***.******@***.***&gt;;
主题:&nbsp;Re: [zhiweichen0012/LCTR] unfair when use exquisite test_transform  (Issue #1)





 
Thank you for your attention to our work, the issue is explained as follows.
 
(1)  The test_transform is also utilized in the CVPR2022 paper (BAS: https://github.com/wpy1999/BAS/blob/869f66bab1b5a472c8b37520fcd6cc6f9770fa10/ILSVRC/BAS_inference.py#L189), which is a common test_transform for WSOL.
 (2) We re-implement the baseline and outperform it, which proves the effectiveness of our approach.
 (3) More importantly, we did not use the ten crop augmentations in the testing phase as other WSOL methods, and we believe that LCTR will get higher performance after using this augmentation.
 
Therefore, it is fair to use the test_transform.
